### ISSUE TITLE
Image slider does no longer work properly

### ISSUE THREAD

**Issue by christianversloot** [PaulBGD/react-native-image-slider#13]
I've followed the development of this package for a few weeks now. Today, I needed it for my app, and installed it according to the installation instructions.

The code that I use is as follows

```
return (
      <ImageSlider height={300} images={[
        'http://placeimg.com/640/480/any',
        'http://placeimg.com/640/480/any',
        'http://placeimg.com/640/480/any'
      ]}/>
    );
```

When running the app, it does show the image slider. However, when scrolling, it just 'scrolls' to the right and left (like a normal ScrollView with horizontally oriented images) and the image dots do no longer "switch".

**Comment by PaulBGD** [comment]
What platform?

**Comment by christianversloot** [comment]
android, rn 0.33, no errors, rather than described above

**Comment by PaulBGD** [comment]
Okay, looking over the issue it appears that Android does not like a PanResponder on a ScrollView at all. Which is a shame, because Android also does not support any of the props that iOS does to make an Image Slider.

For Android I'm probably going to have to listen to onScroll, then once it stops for more than a few hundred milliseconds bounce the slider into the right position.

@christianversloot For now I suggest using an older version of the project on Android.

**Comment by christianversloot** [comment]
@PaulBGD Which version do you recommend?

**Comment by PaulBGD** [comment]
1.0.3 should work fine for both Android and iOS.

**Comment by PaulBGD** [comment]
Closing due to no response.

**Comment by wasa4587** [comment]
yes, 1.0.3  works for both

**Comment by shridharmalagi** [comment]
how to get 1.0.3

**Comment by NishithHM** [comment]
Hi I am just getting blank scree, no image is being rendered
